apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser
spec:
  replicas: 3
  selector:
    matchLabels:
      app: parser
  template:
    metadata:
      labels:
        app: parser
    spec:
      containers:
      - name: parser
        image: alexisnunez957/csc468cloud:parser
        ports:
        - containerPort: 80
